#!/usr/bin/env bash
# Strict host key checking must be disabled when using scp
if [ $# -lt 3 ]; then
	echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 99
fi

if [ $# -eq 3 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
