#!/usr/bin/env bash
#The redirection must be a “301 Moved Permanently”

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com/shorts/qrt7PMcsQms?si=JkPXx59ExZDm7en1;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
sudo service nginx restart
