#!/usr/bin/env bash
#The redirection must be a “301 Moved Permanently”

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
Updated_Rule="server_name _;\\n\\trewrite ^/redirect_me https://youtube.com/shorts/qrt7PMcsQms?si=JkPXx59ExZDm7en1 permanent;"
sudo sed -i "s#server_name _;#$Updated_Rule#" /etc/nginx/sites-enabled/default
sudo service nginx restart
