#!/usr/bin/env bash
#The redirection must be a “301 Moved Permanently”

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
Updated_Rule="server_name _;\\n\\trewrite ^/redirect_me https://youtube.com/shorts/qrt7PMcsQms?si=JkPXx59ExZDm7en1 permanent;"
sudo sed -i "s#server_name _;#$Updated_Rule#" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
if ! grep -q "error_page 404 /cuctom_404.html;" /etc/nginx/sites-enabled/default; then
    Updated_Rule="listen 80 default_server;\\n\terror_page 404 /custom_404.html;\\n\\tlocation = /custom_404.html {\\n\\t\\tinternal;\\n\\t}"
    sudo sed -i "s#listen 80 default_server;#$Updated_Rule#" /etc/nginx/sites-enabled/default
fi
sudo service nginx restart
sudo service nginx reload
