#!/usr/bin/env bash
#The redirection must be a “301 Moved Permanently”

sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '53r /dev/stdin' /etc/nginx/sites-enabled/default <<< "        location /redirect_me {
                 return 301 https://youtube.com/shorts/qrt7PMcsQms?si=JkPXx59ExZDm7en1;
        }"
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '53r /dev/stdin' /etc/nginx/sites-enabled/default <<< "        error_page 404 /custom_404.html;
        location = /custom_404.html {
                 root /var/www/html;
                 internal;
        }"
sudo service nginx restart
