#!/usr/bin/env bash
#hii ni ujinga
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

if ! grep -q "location /redirect_me {" /etc/nginx/sites-enabled/default; then
sudo sed -i '/server_name _;/a'\
        'location \/redirect_me {'\
            'return 301 https:\/\/youtu.be\/8Hyv_tjXz6k?si=srknvG0XwpGmhxe4;'\
        '}' /etc/nginx/sites-enabled/default
fi

if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-enabled/default; then
sudo sed -i '/server_name _;/a'\
        'error_page 404 /404.html;' /etc/nginx/sites-enabled/default
fi

if ! grep -q "add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default; then
sudo sed -i '47i\        add_header X-Served-By \$hostname;' /etc/nginx/sites-enabled/default
fi
sudo service nginx restart
