#!/usr/bin/env bash

# Update system packages
sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install -y haproxy
#enabling and starting
sudo service haproxy start
sudo service haproxy enable
# Configure HAProxy
#sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

muhindi="
frontend myfrontend
    bind *:80
    default_backend mybackend

backend mybackend
    balance roundrobin
    server 471194-web-01 54.208.23.155:80 check
    server 471194-web-02 34.239.255.201:80 check
    "
echo "$muhindi" | sudo tee -a /etc/haproxy/haproxy.cfg
# Restart HAProxy
sudo service haproxy restart
# Verify HAProxy status
sudo service haproxy status
