#!/usr/bin/env bash
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed and pings 5 times


if [ "$#" -ne 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
fi
