#!/usr/bin/env bash
#shell

PID_FILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start()
{
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running."
    else
        $SCRIPT &
        echo $! > "$PID_FILE"
        echo "manage_my_process started."
    fi
}

stop()
{
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped."
    else
        echo "manage_my_process is not running."
    fi
}

restart()
{
    stop
    start
    echo "manage_my_process restarted."
}

usage()
{
    echo "Usage: $0 {start|stop|restart}"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        usage
        ;;
esac
