#!/bin/bash
# Set the field separator then display story

IFS=:
while read -r username password uid gid full_name home_directory shell
do
    echo "The user $username is part of the $gid gang, lives in $home_directory, and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd
