#!/bin/bash
# Set the field separator then display story

IFS=:
while read -r username password uid gid full_name home_directory shell
do
    echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd
