#!/usr/bin/env bash
# display best school*9 then hi then bestschool

count=1
while ((count <= 10)); do
    echo "Best School"

    if ((count == 9)); then
        echo "Hi"
    fi

    ((count++))
done
