#!/usr/bin/env bash
# changes permission nginx.conf,stop Apache,
	mod to listen on 8080,start nginx under user.
sudo chmod 777 /etc/nginx/nginx.conf
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
